#ifndef PIL_OVERLAY_EXAMPLE_DIRECTX_TEST_WINDOW_RESOURCE_H
#define PIL_OVERLAY_EXAMPLE_DIRECTX_TEST_WINDOW_RESOURCE_H

#define HLSL 101
#define IDR_SHADER 104

#endif //PIL_OVERLAY_EXAMPLE_DIRECTX_TEST_WINDOW_RESOURCE_H
